### ISSUE TITLE
Error message is hidden when form control loses focus

### ISSUE THREAD

**Issue by railsstudent** [tilwinjoy/angular-bootstrap-material#14]
I observe that error message of form control is hidden when it loses focus.
This behaviour does not match the requirement of the project i am currently working on.

Is it possible to retain the message when form control loses focus?
This is the template code found in form-group.html

```html
<div ng-show="showErrors" ng-messages="this['fg_'+$id].$error" ng-messages-multiple>
    <div ng-if="errorMessagesInclude" ng-messages-include="{{errorMessagesInclude}}"></div>
    <div ng-repeat="(key,value) in errorMessageMap">
      <!-- use ng-message-exp for a message whose key is given by an expression -->
      <div ng-message-exp="key" class="help-block">{{value}}</div>
    </div>
  </div>
```
Thanks,

Connie

**Comment by tilwinjoy** [comment]
Hi, as mentioned in [contributiob guidelines](https://github.com/tilwinjoy/angular-bootstrap-material/blob/master/CONTRIBUTING.md#bug-reports) this project doesn't handle any CSS on it's own.
This is the behavior of bootstrap material design project. There is an issue related to this - FezVrasta/bootstrap-material-design#887. Please vote/voice your opinion/submit a PR in it.

As far as I remember this is handled via CSS selectors (Something like "hide all error messages, only display the errors inside `has-focus` parent") you can easily override it locally as well...
