### ISSUE TITLE
Bower version out-of-date - New tag needed

### ISSUE THREAD

**Issue by danielfariati** [tilwinjoy/angular-bootstrap-material#5]
Hi.

The last tag we have is based on this commit https://github.com/tilwinjoy/angular-bootstrap-material/commit/011301a1f3661a7ced708dd91c6895836c79e91a.

Because of that, the bower version is out-dated and some things don't work properly (like the floating labels).

I think it's time to create a new tag.

Thanks!

**Comment by tilwinjoy** [comment]
Hi, Thanks for the reminder. I have pushed a new tag.
