### ISSUE TITLE
Not able to add input with prefix icon

### ISSUE THREAD

**Issue by RudineyMejias** [tilwinjoy/angular-bootstrap-material#6]
Here's the example.

![image](https://cloud.githubusercontent.com/assets/7003090/16621856/fdb7fdc2-4354-11e6-967c-8f4a79f63810.png)

**Comment by tilwinjoy** [comment]
Hi,
 I can't figure out what's the issue based on an image. Did you try the mark up given in [bootstrap material design docs](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#forms)?

Please create an online demo as mentioned in the [contribution guidelines](https://github.com/tilwinjoy/angular-bootstrap-material/blob/master/CONTRIBUTING.md#bug-reports)
